SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Attendance](
    [Id] [bigint] IDENTITY(1,1) NOT NULL,
    [WorkshopId] bigint FOREIGN KEY REFERENCES Workshops(Id),
    [PersonId] bigint FOREIGN KEY REFERENCES People(Id)
 CONSTRAINT [PK_Attendance] PRIMARY KEY CLUSTERED
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO